const projects=[
{title:'BONPAY',category:'Fintech',description:'A next-generation African digital banking concept for Niger and Francophone West Africa, focused on simple, fast and trustworthy everyday payments.',stack:['React Native','Expo','TypeScript','Node.js','PostgreSQL'],status:'Product concept',accent:'lime'},
{title:'NOURY Travel',category:'Web',description:'Premium Hajj, Umrah and international travel experience with an editorial luxury direction, package discovery and direct enquiry journeys.',stack:['React','TypeScript','Vite','Responsive UI'],status:'Website build',accent:'gold'},
{title:'KUM SMS',category:'EdTech',description:'Academic management suite concept for student records, dashboards, administration workflows and a modern institutional interface.',stack:['React','TypeScript','PHP','Bootstrap'],status:'Academic project',accent:'cyan'},
{title:'Web3 Hunt',category:'Web3',description:'A premium opportunity discovery brand concept for a community tracking airdrops, launches, campaigns and ecosystem updates.',stack:['Brand UI','Web3','Community','Social'],status:'Brand concept',accent:'violet'},
{title:'Airdrop Radar',category:'Web3',description:'Concept dashboard for organizing crypto opportunities by ecosystem, status, task type and personal progress.',stack:['React','Dashboard UI','Data UX'],status:'Concept build',accent:'pink'},
{title:'Been-Usman Phone Store',category:'Branding',description:'Premium retail identity and digital campaign direction for a modern smartphone and accessories business.',stack:['Brand Identity','UI Design','Creative'],status:'Brand concept',accent:'orange'},
{title:'Community OS',category:'Product',description:'A concept operating layer for communities: member discovery, announcements, campaigns and opportunity feeds in one interface.',stack:['Product Design','UX','React'],status:'Concept build',accent:'blue'},
{title:'Fintech UI Kit',category:'UI/UX',description:'A reusable interface direction for African fintech products, combining clean information hierarchy with high-trust visual language.',stack:['Design System','UX','Components'],status:'Design concept',accent:'emerald'},
{title:'Travel Ops Console',category:'Dashboard',description:'Internal operations dashboard concept for package management, enquiries, schedules, customers and travel support workflows.',stack:['Dashboard','React','Data UX'],status:'Concept build',accent:'amber'}
];
const categories=['All',...new Set(projects.map(p=>p.category))];
const filters=document.querySelector('#filters'), grid=document.querySelector('#projects');
function renderFilters(){filters.innerHTML=categories.map(c=>`<button class="${c==='All'?'active':''}" data-filter="${c}">${c}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{filters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)}))}
function render(filter='All'){const list=filter==='All'?projects:projects.filter(p=>p.category===filter);grid.innerHTML=list.map((p,i)=>`<article class="project accent-${p.accent}"><div class="project-visual"><div class="visual-lines"></div><div class="visual-window"><div class="window-dots"><i></i><i></i><i></i></div><div class="fake-ui"><div class="ui-sidebar"></div><div class="ui-body"><span></span><span></span><span></span><div class="ui-chart"></div></div></div></div><span class="project-index">0${i+1}</span></div><div class="project-info"><div class="project-meta"><span>${p.category}</span><span>${p.status}</span></div><h3>${p.title}</h3><p>${p.description}</p><div class="stack">${p.stack.map(s=>`<span>${s}</span>`).join('')}</div><a href="#contact" class="project-link">View case study ↗</a></div></article>`).join('')}
renderFilters();render();
document.querySelector('#menu').addEventListener('click',()=>document.querySelector('#navLinks').classList.toggle('open'));
document.querySelectorAll('#navLinks a').forEach(a=>a.addEventListener('click',()=>document.querySelector('#navLinks').classList.remove('open')));
